import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/navbar"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="grid grid-rows-[auto_1fr] min-h-screen bg-zinc-100 font-sans dark:bg-black p-1">
        <Navbar/>
        {children}
      </div>
      </body>
    </html>
  );
}
